services:
  - type: web
    name: aurora-music-api
    env: node
    rootDir: .
    buildCommand: npm install && npm run build --workspace packages/shared && npm run build --workspace apps/api
    startCommand: npm --workspace apps/api run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_ORIGIN
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
